DROP VIEW IF EXISTS Message;
DROP VIEW IF EXISTS MessageThread;
DROP VIEW IF EXISTS Person_likes_Message;
DROP VIEW IF EXISTS Message_hasTag_Tag;
DROP VIEW IF EXISTS Country;
DROP VIEW IF EXISTS City;
